package ibc

// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/DFWallet/anatha/x/ibc/keeper
// ALIASGEN: github.com/DFWallet/anatha/x/ibc/types

import (
	host "github.com/DFWallet/anatha/x/ibc/24-host"
	"github.com/DFWallet/anatha/x/ibc/keeper"
	"github.com/DFWallet/anatha/x/ibc/types"
)

const (
	ModuleName   = host.ModuleName
	StoreKey     = host.StoreKey
	QuerierRoute = host.QuerierRoute
	RouterKey    = host.RouterKey
)

var (
	// functions aliases
	NewKeeper           = keeper.NewKeeper
	NewQuerier          = keeper.NewQuerier
	RegisterCodec       = types.RegisterCodec
	RegisterInterfaces  = types.RegisterInterfaces
	DefaultGenesisState = types.DefaultGenesisState
)

type (
	Keeper       = keeper.Keeper
	GenesisState = types.GenesisState
)
